import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  const mapsData = [
    {
      title: "Taiwan Code Camp",
      description: "Official Website",
      link: "https://taiwancodecamp.com/",
    },
    {
      title: "Taiwan Code Camp",
      description: "Official Website",
      link: "https://taiwancodecamp.com/",
    },
    {
      title: "Taiwan Code Camp",
      description: "Official Website",
      link: "https://taiwancodecamp.com/",
    },
  ];
  return (
    <div className={styles.container}>
      <Head>
        <title>Taiwan Code Camp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Taipei Maps</h1>

        {/* <p className={styles.description}>description</p> */}
        <div className={styles.grid}>
          {mapsData.map(({ id, description, title, link }) => (
            <a
              href={link}
              className={styles.card}
              key={title + description.length}
            >
              <h2>{title}</h2>
              {/* <h2>{title} &rarr;</h2> */}
              <p>{description}</p>
            </a>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a rel="noopener noreferrer">Powered by TCC&apos;𝖘 𝕬𝖘𝖘</a>
      </footer>
    </div>
  );
}
